# Use Node.js 23.1.0-alpine for a lightweight, specific version
ARG NODE_VERSION=23.4.0-alpine

FROM node:${NODE_VERSION} AS base

# Set the working directory inside the container
WORKDIR /app

# Create a non-root user for security
USER node

# Copy dependency files and install dependencies with root user
COPY package.json package-lock.json ./

#Install the dependencies
RUN npm install --silent

# Expose the port used by the Next.js development server
EXPOSE 3000

# Default command to start the development server
CMD ["npm", "run", "dev"]
